version: "3"

services:
  frontend:
    restart: always
    ports: []
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf

  backend:
    restart: always
    ports: []
    command: gunicorn -b 0.0.0.0:8000 -w 2 backend.wsgi 

  stock_worker:
    restart: always

  proxy:
    restart: always
