version: "3"

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf

  backend:
    restart: always
    command: ./entrypoint.sh

  stock_worker:
    restart: always

  proxy:
    restart: always
