version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      - DEBUG=1

  frontend:
          #logging:
            #  driver: none
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app

  stock_worker:
    build:
      context: ./stock_worker
    depends_on:
      - backend
    links:
      - backend

  proxy:
    image: "nginx:alpine"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/ssl/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    links:
      - backend
      - frontend

