# Generated by Django 3.0.7 on 2020-07-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderedpost',
            name='posted_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='comment_images'),
        ),
    ]
