# Generated by Django 3.0.7 on 2020-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ref_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='renderedpost',
            name='status',
            field=models.CharField(choices=[('AC', 'accepted'), ('UN', 'unaccepted'), ('RE', 'rejected'), ('PO', 'posted')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
