# Generated by Django 3.0.7 on 2020-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0002_auto_20200712_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
