# Generated by Django 3.0.7 on 2020-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0003_project_platform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platform_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
