ORIGINAL_POST_ID = 'original_post_id'
RENDERED_POST_ID = 'rendered_post_id'
POST_ID = 'post_id'
POST_TYPE = 'post_type'
POST_TYPE_ORIGINAL = 'original'
POST_TYPE_RENDERED = 'rendered'
REPLACE = 'replace'

AS_ORIGINAL = 'as_original'

FONT = 'font'

IMG = 'img'
IMG_COUNT = 'img_count'
IMG_WITH_TEXT = 'img_with_text'
IMG_WITH_IMG = 'img_with_img'
IMG_TEXT_FROM = 'img_text_from'
IMG_TEXT_ORIGINAL = 'original'
IMG_TEXT_COMMENT = 'comment'
IMG_COMMENT_ID = 'img_comment_id'
IMG_TEXT_LOCATION = 'img_text_location'
IMG_TEXT_WITH_REF = 'img_text_with_ref'
IMG_TEXT_WITH_COMMENT_IMG = 'img_text_with_comment_img'
BOTTOM = 'bottom'
TOP = 'top'
